# Security Routes
fos_user_security_login:
    path:  /login
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
    path:  /login_check
    defaults: { _controller: FOSUserBundle:Security:check }

fos_user_security_logout:
    path:  /logout
    defaults: { _controller: FOSUserBundle:Security:logout }

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

# Layout Routes
cornershort_mlmapp_layout_sidebar_menu:
    path:     /layout/sidebarMenu
    defaults: { _controller: CornershortMLMappBundle:Default:sidebarMenu }

cornershort_mlmapp_layout_page_header:
    path:     /layout/pageHeader
    defaults: { _controller: CornershortMLMappBundle:Default:pageHeader }

# Menu Maintenance Pages
cornershort_menu_list_children:
    path:     /menu/children
    defaults: { _controller: CornershortMLMappBundle:MenuWeb:listChildren }

cornershort_menu_view_child:
    path:     /menu/child/{id}
    defaults: { _controller: CornershortMLMappBundle:MenuWeb:viewChild }

cornershort_menu_list_parents:
    path:     /menu/parents
    defaults: { _controller: CornershortMLMappBundle:MenuWeb:listParents }

cornershort_menu_view_parent:
    path:     /menu/parent/{id}
    defaults: { _controller: CornershortMLMappBundle:MenuWeb:viewParent }

# Home Layout Control Pages
cornershort_mlmapp_homepage:
    path:     /
    defaults: { _controller: CornershortMLMappBundle:HomeWeb:index }

# Show New Members Layout Control Pages
cornershort_mlmapp_register_member_page_show:
    path:     /member/show-members
    defaults: { _controller: CornershortMLMappBundle:RegisterMemberWeb:show }

# Add New Member Layout Control Pages
cornershort_mlmapp_register_member_page_add:
    path:     /member/add
    defaults: { _controller: CornershortMLMappBundle:RegisterMemberWeb:add }

# Auto Request For Upgrade Layout Control Pages
cornershort_mlmapp_request_for_upgrade_page_auto:
    path:     /member/request/upgrade-auto
    defaults: { _controller: CornershortMLMappBundle:RequestForUpgradeWeb:auto }

# Manual Request For Upgrade Layout Control Pages
cornershort_mlmapp_request_for_upgrade_page_manual:
    path:     /member/request/uprade-manual
    defaults: { _controller: CornershortMLMappBundle:RequestForUpgradeWeb:manual }

# Manual Upgrade Member Layout Control Pages
cornershort_mlmapp_upgrade_member_page_manual:
    path:     /member/upgrade-member/manual/by-level
    defaults: { _controller: CornershortMLMappBundle:UpgradeMemberWeb:manual }

# Manual Upgrade Member by Product - Admin Tools Layout Control Pages
cornershort_mlmapp_admin_tools_page_upgrade_member_manual:
    path:     /member/upgrade-member/manual/by-product
    defaults: { _controller: CornershortMLMappBundle:AdminToolsWeb:upgradeMemberManualShow }

# Family Tree Layout Control Pages
cornershort_mlmapp_family_tree_page:
    path:     /member/family-tree
    defaults: { _controller: CornershortMLMappBundle:FamilyTreeWeb:index }

# Show User Account Layout Control Pages
cornershort_mlmapp_user_account_page_show:
    path:     /member/user-account/show
    defaults: { _controller: CornershortMLMappBundle:UserAccountWeb:show }

# Edit User Account Layout Control Pages
cornershort_mlmapp_user_account_page_edit:
    path:     /member/user-account/edit
    defaults: { _controller: CornershortMLMappBundle:UserAccountWeb:edit }

# Show Member's Info - Admin Tools Layout Control Pages
cornershort_mlmapp_admin_tools_page_member_info_show:
    path:     /member/member-info/show
    defaults: { _controller: CornershortMLMappBundle:AdminToolsWeb:memberInfoShow }

# Show Member's Payment History - Admin Tools Layout Control Pages
cornershort_mlmapp_admin_tools_page_member_payment_history_show:
    path:     /member/member-info/payment-history
    defaults: { _controller: CornershortMLMappBundle:AdminToolsWeb:memberPaymentHistoryShow }

# Sales Tab 1 - Admin Report Layout Control Pages
cornershort_mlmapp_report_page_sales_tab_1:
    path:     /member/admin-report/sales-tab-1
    defaults: { _controller: CornershortMLMappBundle:AdminReportWeb:salesTab1 }

# Sales Tab 2 - Admin Report Layout Control Pages
cornershort_mlmapp_report_page_sales_tab_2:
    path:     /member/admin-report/sales-tab-2
    defaults: { _controller: CornershortMLMappBundle:AdminReportWeb:salesTab2 }

# Sales Tab 3 - Admin Report Layout Control Pages
cornershort_mlmapp_report_page_sales_tab_3:
    path:     /member/admin-report/sales-tab-3
    defaults: { _controller: CornershortMLMappBundle:AdminReportWeb:salesTab3 }

# Show Bank Widthrawal - Admin Report Layout Control Pages
cornershort_mlmapp_report_page_bank_withdraw_show:
    path:     /member/admin-report/show-bank-withdraw
    defaults: { _controller: CornershortMLMappBundle:AdminReportWeb:bankWithdrawShow }

# Add Bank Widthrawal - Admin Report Layout Control Pages
cornershort_mlmapp_report_page_bank_withdraw_add:
    path:     /member/admin-report/add-bank-withdraw
    defaults: { _controller: CornershortMLMappBundle:AdminReportWeb:bankWithdrawAdd }

# Edit Bank Widthrawal - Admin Report Layout Control Pages
cornershort_mlmapp_report_page_bank_withdraw_edit:
    path:     /member/admin-report/edit-bank-withdraw/{id}
    defaults: { _controller: CornershortMLMappBundle:AdminReportWeb:bankWithdrawEdit }

# Demo Payment Page
cornershort_mlmapp_demo_payment_page_view:
    path:     /member/demo-payment/view/{order}
    defaults: { _controller: CornershortMLMappBundle:Demo_Payment:view }

cornershort_mlmapp_demo_payment_page_new:
    path:     /member/demo-payment/new
    defaults: { _controller: CornershortMLMappBundle:Demo_Payment:new }
