# Default Layout Control Pages
cornershort_mlmapp_homepage:
    path:     /
    defaults: { _controller: CornershortMLMappBundle:Default:index }

cornershort_mlmapp_layout_sidebar_menu:
    path:     /layout/sidebarMenu
    defaults: { _controller: CornershortMLMappBundle:Default:sidebarMenu }

cornershort_mlmapp_layout_page_header:
    path:     /layout/pageHeader
    defaults: { _controller: CornershortMLMappBundle:Default:pageHeader }

# Menu Maintenance Pages
cornershort_menu_list_children:
    path:     /menu/children
    defaults: { _controller: CornershortMLMappBundle:MenuWeb:listChildren }

cornershort_menu_view_child:
    path:     /menu/child/{id}
    defaults: { _controller: CornershortMLMappBundle:MenuWeb:viewChild }

cornershort_menu_list_parents:
    path:     /menu/parents
    defaults: { _controller: CornershortMLMappBundle:MenuWeb:listParents }

cornershort_menu_view_parent:
    path:     /menu/parent/{id}
    defaults: { _controller: CornershortMLMappBundle:MenuWeb:viewParent }
