# Security Routes
fos_user_security_login:
    pattern:  /login
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
    pattern:  /login_check
    defaults: { _controller: FOSUserBundle:Security:check }

fos_user_security_logout:
    pattern:  /logout
    defaults: { _controller: FOSUserBundle:Security:logout }

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

# Layout Routes
cornershort_mlmapp_layout_sidebar_menu:
    path:     /layout/sidebarMenu
    defaults: { _controller: CornershortMLMappBundle:Default:sidebarMenu }

cornershort_mlmapp_layout_page_header:
    path:     /layout/pageHeader
    defaults: { _controller: CornershortMLMappBundle:Default:pageHeader }

# Menu Maintenance Pages
cornershort_menu_list_children:
    path:     /menu/children
    defaults: { _controller: CornershortMLMappBundle:MenuWeb:listChildren }

cornershort_menu_view_child:
    path:     /menu/child/{id}
    defaults: { _controller: CornershortMLMappBundle:MenuWeb:viewChild }

cornershort_menu_list_parents:
    path:     /menu/parents
    defaults: { _controller: CornershortMLMappBundle:MenuWeb:listParents }

cornershort_menu_view_parent:
    path:     /menu/parent/{id}
    defaults: { _controller: CornershortMLMappBundle:MenuWeb:viewParent }

# Home Layout Control Pages
cornershort_mlmapp_homepage:
    path:     /
    defaults: { _controller: CornershortMLMappBundle:HomeWeb:index }

# Show New Members Layout Control Pages
cornershort_mlmapp_register_member_page_show:
    path:     /show_member
    defaults: { _controller: CornershortMLMappBundle:RegisterMemberWeb:show }

# Add New Member Layout Control Pages
cornershort_mlmapp_register_member_page_add:
    path:     /add_member
    defaults: { _controller: CornershortMLMappBundle:RegisterMemberWeb:add }


# Request For Upgrade Layout Control Pages
cornershort_mlmapp_request_for_upgrade_page:
    path:     /request_for_upgrade
    defaults: { _controller: CornershortMLMappBundle:RequestForUpgradeWeb:index }

# Upgrade Member Layout Control Pages
cornershort_mlmapp_upgrade_member_page:
    path:     /upgrade_member
    defaults: { _controller: CornershortMLMappBundle:UpgradeMemberWeb:index }

# Family Tree Layout Control Pages
cornershort_mlmapp_family_tree_page:
    path:     /family_tree
    defaults: { _controller: CornershortMLMappBundle:FamilyTreeWeb:index }

# Show User Account Layout Control Pages
cornershort_mlmapp_user_account_page_show:
    path:     /show_user_account
    defaults: { _controller: CornershortMLMappBundle:UserAccountWeb:show }

# Edit User Account Layout Control Pages
cornershort_mlmapp_user_account_page_edit:
    path:     /edit_user_account
    defaults: { _controller: CornershortMLMappBundle:UserAccountWeb:edit }

# User Management Layout Control Pages
cornershort_mlmapp_user_management_page:
    path:     /user_management
    defaults: { _controller: CornershortMLMappBundle:UserManagementWeb:index }

# Report Layout Control Pages
cornershort_mlmapp_report_page:
    path:     /report
    defaults: { _controller: CornershortMLMappBundle:ReportWeb:index }

# Default Layout Control Pages
cornershort_mlmapp_defaultpage:
    path:     /
    defaults: { _controller: CornershortMLMappBundle:Default:index }
