<?php

namespace Cornershort\MLMappBundle\Repository;

/**
 * BankWithdrawalHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BankWithdrawalHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
