<?php

namespace Cornershort\MLMappBundle\Repository;

/**
 * MemberPaymentHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MemberPaymentHistoryRepository extends \Doctrine\ORM\EntityRepository
{
}
